#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'development');

/**
 * 第三方的自动加载
 */
require(__DIR__ . '/../common/config/autoload.php');
require(__DIR__ . '/../vendor/autoload.php');

require(__DIR__ . '/../vendor/yii2/framework/Yii.php');
require(__DIR__ . '/../common/config/bootstrap.php');
require(__DIR__ . '/config/bootstrap.php');

$config = \common\helpers\CommonHelper::loadConfig('main.php',['@common','@console']);

$application = new \yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
